### ISSUE TITLE
[ Feat ] SMS Support

### ISSUE THREAD

**Issue by toddheslin** [dev-xo/remix-auth-totp#15]
At the moment there's an explicit dependency on an `email` throughout the strategy. However, it feels like this could easily support both email or text message (sms).

Whilst the whole strategy could be forked and we could have `otp-email` and `otp-sms`, it feels like the existing API could allow for the developer to implement their own logic in the `sendCode()` function -> If there's an email, send an email, or if there is a phone number, send a text message.

Thoughts?

**Comment by dev-xo** [comment]
Sounds good to me @toddheslin and I was thinking about it before.

The main objective for me with this Strategy and package was to keep things as easy as possible for the developer, besides we have to configure a few things _(database, cookie storage, email provider)_ for it to start doing what's expected to do.

Saying that, I would like to keep improving the Strategy over time and adding features that could make it better for the community. Sadly I don't have that much time lately. 

Do you have any idea about how this could be approached? 
Making the OTP transport a generic could be a start right?

Not sure how much time you have, or if you are able to contribute, but in case you do, feel free to create pull request with your own approach.

I will look into this, not sure when but for sure I will, meanwhile we can keep talking or looking for approaches to make this possible. Thanks for your suggestion!

**Comment by toddheslin** [comment]
Nice thinking @dev-xo - on the same page. I like the abstractions you've put in place. It was super easy to implement.

I will want to support SMS at some point, so will open a PR if you don't get to it before me.

**Comment by dev-xo** [comment]
Take your time and go for it @toddheslin, I got time for an extended code review to your approach!

As I said before, right now I can't start implementing it by myself (lack of time) but for sure I will at some point, unless you figure it before and decide to contribute to the package. 

Gonna leave the Issue open in case you wanna share some thoughts or keep this talk up.

**Comment by leimantas** [comment]
But you can just send SMS in `sendCode` with Twilio. And you are done. 

[https://www.twilio.com/docs/sms/quickstart/node](https://www.twilio.com/docs/sms/quickstart/node)

**Comment by dev-xo** [comment]
Not sure if you're still interested in this @toddheslin, but Remix Auth OTP will become a TOTP package that could also support 2FA authentication.

Not related to SMS at all, but the new Strategy will allow easier implementation of SMS and other similar features.

_The repo / package has not been released yet. It will be in the next few hours. Just renaming things and preparing the repository for it._

**Comment by toddheslin** [comment]
Thanks @dev-xo for the heads up on the package name change. I stuck with just using email for now so never got around do doing SMS. However I like the clear direction. Kudos!

**Comment by dev-xo** [comment]
Some breaking changes has been made into this rewrite @toddheslin  _(not only the rename)_

Feel free to check the [Examples](https://github.com/dev-xo/remix-auth-totp/blob/main/docs/examples.md) folder in case you need to have a look.

Thanks for the reply.
Closing this for now @toddheslin.
