### ISSUE TITLE
[ Feat ] 2FA Authentication Support

### ISSUE THREAD

**Issue by dev-xo** [dev-xo/remix-auth-totp#21]
A work in progress is already underway to introduce support for **2FA authentication**, leveraging the capabilities of [`@epic-web/totp`](https://github.com/epicweb-dev/totp).

Suggestions and PRs are welcome! 🙏

**Comment by Sarvesh-Ghildiyal** [comment]
Hello @dev-xo,
In the 2FA, first we are going to authenticate the user based on the email and password registered in Database then with the TOTP?

**Comment by dev-xo** [comment]
Would love to give you a proper response to that, @Sarvesh-Ghildiyal, but there aren't plans yet for 2FA Implementation yet, and the ones that were in progress were stopped some time ago.

We'll probably revisit this soon!

**Comment by Sarvesh-Ghildiyal** [comment]
Thanks for the update @dev-xo, Really appreciate it!

**Comment by stephen776** [comment]
Any updates here? Or will this strategy continue to focus on magic-link style auth?

**Comment by dev-xo** [comment]
Hello @stephen776! Not sure what to say, I'm always up to look into solutions or new features, although pretty busy nowadays, so if you are up to come up with something, we may be able to look into it!
