### ISSUE TITLE
How to reset verify state?

### ISSUE THREAD

**Issue by andersr** [dev-xo/remix-auth-totp#22]
Hi,  I've integrated your TOTP strategy and everything works great when following a normal verify flow. 

However, once a verify code has been sent, **it's not clear how to reset the login view to the default state**, eg for entering a different email, or if there was an exception of some sort.

I tried both expiring the `'auth:email'` cookie as well as destroying the current session, but neither appears to work.  I am thinking it might be necessary to delete the corresponding totp record in the db but not clear where to do that.

Another alternative would be have verify be a separate route, which you [alluded to](https://github.com/dev-xo/remix-auth-totp#logintsx) in the docs. However, I wasn't clear on how one would split up login and verify into different routes.

Any tips or insights would be appreciated!

**Comment by dev-xo** [comment]
Hello @andersr! Good question actually. 

I usually tend up to remove the cookie from the browser, but I think users should not do that, instead we should provide an easy way for them to enter another email, or simply reset the login flow.

Gonna look into it, and I will come up with an example for you.
_(Just woke up, sorry for the late response!)_

**Comment by dev-xo** [comment]
Check the new [Starter Example](https://github.com/dev-xo/totp-starter-example) @andersr . It uses a 2-step route to input and verify the authentication.

If you go back to `/login` after inputed the first email, you could enter a different email or simlpy fix the typo from the first one.

On submit, database will invalidate the old OTP.

![Screen Shot 2023-10-02 at 07 14 48](https://github.com/dev-xo/remix-auth-totp/assets/82425492/92045970-e4c7-4a76-9186-274e9a3ffe6e)


Notice me if this is what you was looking for @andersr.
Some new changes and advanced usages will be added soon.

**Comment by andersr** [comment]
@dev-xo thanks for all the great insights and for updating the example to include a separate verify page.  I tried running it and found that if I go back to the login page and submit a new email address, it does send another email, but to the original email rather than the new one.

**Comment by dev-xo** [comment]
Yeah, good point @andersr. 

Noticed the OTP was correctly invalidated but didn't went deeper. 
It has a lot of sense actually. We are probably re-sending the email that's already stored in session.

Ideally, I would want a client-side fix to avoid updating the Strategy.
Otherwise I should come up with a handler that could invalidate the Session on call.

Thanks for noticing! Will looking into it @andersr.

**Comment by dev-xo** [comment]
Yep, already working on a fix for it.

Will be directly on the Strategy, also this will keep the client implementation as it is already.
If the provided form email, is not the one that's stored in session, the authentication flow should reset.

Will probably be ready today.
Thank you for the feedback @andersr!

**Comment by dev-xo** [comment]
`v1.0.4` has been published @andersr.

Feel free to have a look, test it and tell me if everything works as expected

**Comment by andersr** [comment]
@dev-xo pulled the new version and tested it.  Everything works as expected (email address updates on 2nd login)

**Comment by dev-xo** [comment]
Happy to hear that @andersr. Thank you for the feedback! 
Feel free to come up with more ideas / fixes. Them will be welcomed.
