### ISSUE TITLE
[ Refactor ] Verify call before auth flow succeeds

### ISSUE THREAD

**Issue by haus23** [dev-xo/remix-auth-totp#27]
Hi,

thanks a lot for your efforts. I am trying to use your strategy in my app.

One problem: perhaps I do misunderstand something. But I don't get, why the verify-Function is called here. So any User will be created (if not existing) before her/his auth flow completes. Is the User-Object really needed here? 

```
  private async _sendOTP(data: SendTOTPOptions<User>) {
    const user = await this.verify(data)
    await this.sendTOTP({ ...data, user })
  }
```

https://github.com/dev-xo/remix-auth-totp/blob/b3d2d5423b1bbb826ab3c0adfef2b279052e2ae0/src/index.ts#L610C1-L613

Sorry for the noise if it is not related.

Micha

**Comment by dev-xo** [comment]
Hello Micha, don't worry, it's not noise—it's actually a good question.

I'm not sure what the decision behind it was (I'm sure it was a good one at the time), but right now it doesn't feel like the verify method should be called there.

I will look into it, but it will probably be refactored out of the code.
Thanks for noticing!

Daniel

**Comment by dev-xo** [comment]
This has already been addressed, and some of the code has been refactored, @haus23. 
Thank you for bringing it to my attention. 

Feel free to check out the latest [Release v1.3.0](https://github.com/dev-xo/remix-auth-totp/releases/tag/v1.3.0).
