### ISSUE TITLE
[ Refactor ] Store TOTP Data in Session Instead of Database

### ISSUE THREAD

**Issue by mw10013** [dev-xo/remix-auth-totp#43]
`TOTPData` consists of `{hash, active, attempts}`. With database storage, `expiresAt` is also stored in the database so that a clean up routine can delete expired totps.

Currently in session data, we store `hash` and `expiresAt`. To move the storage of `TOTPData` from the database to the session, we need only bring over `attempts` since `active` could be handled with `expiresAt` in session.

Impact of this change

- Slight increase in size of session data due to `attempts`
- Removes `createTOTP`, `readTOTP`, and `updateTOTP` from the API
- Eases application integration since a database is no longer needed and no need to figure out how to delete expired totps.
- The database seems to add little benefit from a security perspective since the TOTP hash is already stored in the session.

The implementation should consolidate all the TOTP data session keys under one session key to reduce top-level session vars.

@dev-xo: Please share your thoughts.

**Comment by dev-xo** [comment]
I will take the time to give a proper response to this today, @mw10013! I've been quite busy these past few days, but I will save some time to look into this and try my best to give you a proper response!

**Comment by dev-xo** [comment]
This is interesting, @mw10013, and a similar approach was about to be taken on the first `remix-auth-otp` _(previous library, that this one has revamped)_.

I remember having a talk with Kent C. Dodds on the Remix Discord about storing everything in the session, and if I'm not wrong, the talk could be summarized in a few security risks exposed to the public. But for that, the secret keys should be leaked first.

I'm not sure if you had the time to look into `@epic-web/totp` and the `Epic-Stack` that also uses this package. If I'm not wrong, the Epic Stack has a similar database-first approach _(I could be wrong)_, and I simply took the "safe path" at that time, and that was, splitting the TOTP into database and session.

I'm not sure if the implementation was the best, although we have a fully functional TOTP authentication strategy for remix-auth.

---

With that said, I'm a big fan of simplifying and keeping the API easy for the consumer, and if there are no security implications, we could look into it.

- This will also mean we would have to move to `v3.0`, right? Not a big fan of that, major version changes in little time could be perceived as a not stable package/library to use.

- Will we have any real security impact of storing everything in the session? What security flaws could we have? (If any)

As always, do this only if you have the time for it. I'm currently happy with the state of the package, although removing API and simplifying its use would be a really great reason to look into!

**Comment by mw10013** [comment]
@dev-xo: Interesting to hear about your discussion with KCD. `Epic-Stack` seems to store both TOTP and session in the database. It also seems to push off the cleanup of expired TOTP's and sessions to some future background job.

`remix-auth-totp` has already made the decision to store security data in the session, namely the TOTP hash. That the TOTP hash is also stored in the database seems to be a point of redundancy and complexity. Hence, the proposal to remove. It doesn't seem to reduce the security in `remix-auth-totp` since the TOTP hash is already in the session.

Moving to `v3.0` so soon is not ideal. One advantage of a Christmas release is that it's doubtful anybody has yet migrated to it and we can slip this in so they only need to do one migration.

As part of this refactor, I'd like to revisit #34 [ Feat ] Make `TOTP_NOT_FOUND` error message customizable and rationalize the errors surrounding TOTP codes. I propose that whenever `remix-auth-totp` handles a TOTP code, it treats it as valid, invalid, or expired and any error messages coming out of that would reflect those states. For example, when `remix-auth-totp` receives a code and there is no TOTP data in the session, it simply returns `TOTP_EXPIRED`, not `TOTP_NOT_FOUND`. And if max attemps are reached, it simply returns `TOTP_EXPIRED`, not `TOTP_INACTIVE`. And if the TOTP data in the session has expired, it would return `TOTP_EXPIRED`.

**Comment by dev-xo** [comment]
Sounds great to me, @mw10013! You've earned my trust with all the amazing work you've already done, so I'm sure this will be a great change, especially if you consider it. At this point, you understand the project and the entire strategy better than me, so if there's something I can learn from the entire process, just go for it.

Although it's not ideal moving that soon to `v3.0`, I could simply announce it later at some point and create the migration files we need for the project.

Also, feel free to reopen issue #34. What you proposed makes a lot of sense and also simplifies the current logic we have for errors.

- - - -

With that said, wishing you a happy new year @mw10013! 
Thanks a lot for all the effort and time you are putting into this!
