### ISSUE TITLE
[ Feat ] Add support for Session ID rotation.

### ISSUE THREAD

**Issue by luismiguelamado** [dev-xo/remix-auth-totp#48]
Hello!
First of all, great work done and I'm happy to join the community of people using this package! :)

I've been playing around with the package and I believe there could be a functionality for Session ID Rotation. 

For example, when using Cloudflare KV, we store encrypted cookie in the user browser and the session in the KV. The session can have a maxAge let's say of 7 days. During these 7 days, I believe there should be a rotation of the session key in the cookie to prevent possible issues in case any person with bad intentions get access to the cookie and try to impersonate the user. For example, if the user login in a public computer and never open the page back. Then when the session is rotated, that token is no longer valid in that computer.

I don't know if is my paranoid mindset for security impacting me. I believe this could improve greatly the security.

What are your thoughts @dev-xo? 

Thank you and hope to collaborate in the package in the near future!

**Comment by mw10013** [comment]
@luismiguelamado: Thanks for looking into `remix-auth-totp` and making this proposal. Can you provide more details on how `remix-auth-totp` could rotate a session id?

`remix-auth-totp` does not create or manage the session. Rather the application does and wonder if it makes sense for the application to choose a session storage implementation that does some sort of rotation. Since `remix-auth-totp` simply uses Remix's `SessionStorage` interface, any session storage implementation details such as rotation or Cloudflare KV are completely transparent to it.

Would a implementation of the `SessionStorage` interface that did the rotation meet your needs?

**Comment by luismiguelamado** [comment]
Hi @mw10013 
Thank you for the quick answer.

I'm no expert in security or in Remix, but I've been for the past days (nights 😆) reading about this and trying to wrap my head in the best solution.

So far, I have a mix of ideas, like leveraging the headers of cloudflare to make some kind of check to extend the session or to associate the session with a specific device fingerprint. 

It's not a good practice to have sessions that last for a really long time, but here is the compromise between user experience and security. 

Honestly, I don't really know how Remix Auth Totp could somehow help with the session management. Probably, this is more related to the Session storage of remix itself. The session storage with key rotation could solve this problem, I believe.

I will continue investigating the best option for it. If you have some ideas, please share :)

**Comment by dev-xo** [comment]
Thank you so much for getting into this talk, @mw10013. As for now, I will leave the issue open in case some new ideas or workarounds come in.

Feel free to share any thoughts or implementations you find to fix your current issue, @luismiguelamado, either from Remix Session itself or any other suggestions you could have for `remix-auth-totp`.

**Comment by luismiguelamado** [comment]
Thank you @dev-xo for the answer!

I've thought of a solution to partially solve this problem without session rotation.

What if each session would have a device fingerprint associated with it? For example, timezone, country, screen width, os, and other relevant elements that would need to be configurated by the developer because shouldn't be public the elements that are part of it.

The scenario would be:

1. User logins
2. In KV, the session would have a fingerprintKey that is an encrypted string with the metadata.
3. On every request, the device fingerprint would be generated and compared with the one in the session.
4. If it doesn't match, then the user would be logged out.

While this can still be hijacked, it wouldn't allow the same session in two different devices. When coupled with session rotation every 30 minutes to 1 hour, it would make an improvement in terms of security and guarantee really an extra level of security.

Just brainstorming :)

**Comment by haus23** [comment]
Hey, I'm sure that - as @mw10013 stated - this libray can't do something like rotating the session key. The session "comes" from the user/client/coder and is just used. You can do the rotating by yourself and the user (good) would have been redirected to the login page. The other (bad) user as well.
