### ISSUE TITLE
Example flow seems non-standard

### ISSUE THREAD

**Issue by justin-hackin** [dev-xo/remix-auth-totp#58]
I am implementing OTP magic link flow only for the purposes of frictionless login. I know there are security advantages to no-password flows but security breaches are of minimal impact to the users of my project.

When I looked at the example, I noticed that you have the user manually enter the OTP. In a "magic link" flow, I expect to be able to log in without having to enter a password or code. 

Is there a particular reason why this example doesn't just encode the OTP in the URL and then give either: a confirmation with a navigation link to proceed OR a failure message with a link to try the flow again?

**Comment by dev-xo** [comment]
Hello, Justin. 
- About which example are you referring exactly?

The user can enter the OTP manually, or via a magic link where they simply either click a link (or press a button, for better UX). If your intention is simply for the user to not manually enter the OTP, probably you can simply hide that part of the UI and make the user click the link sent to the email.

The "example" (not sure which of them), is created to let the Developer know how to handle different situations, not just one, probably the one you are describing.

I would appreciate more details in your case, and even opening an issue or creating a PR if you think `remix-auth-totp` could handle things differently, or if simply you want to add value to it.

**Comment by justin-hackin** [comment]
Thanks for quickly taking interest in my problem. I was working with https://github.com/dev-xo/totp-starter-example . I just put a breakpoint in the sendOTP function in it to discover that the magicLink _does_ have a `code` query param that the authenticator handles internally. So, really, I don't have to add anything special, I just need to remove the inputs and it's good the example has this because you can see how to authenticate programmatically 👍 Might be nice to have a quick note about magic link URL anatomy in docs but perhaps this should have been obvious.

**Comment by dev-xo** [comment]
Gonna delete this issue @justin-hackin as I noticed passive-aggressive tone which I don't like to see around the library. Also, you didn't even stared the project but complained about it already.

We are here in case you need something else.
Daniel.
