### ISSUE TITLE
[ Fix ] Error in Node 20+

### ISSUE THREAD

**Issue by markhker** [dev-xo/remix-auth-totp#68]
The published version of the "thirty-two" npm package is outdated, making use of `new Buffer` in the code, causing some errors (tested in AWS Lambda) and it's impossible to encode/decode with those settings, also the @epic-web/totp package (used by this lib) has the same issue.

**Comment by dev-xo** [comment]
Interesting, also good to know @markhker.

We are leveraging those packages as it offers us a solution to avoid implementing some of the functionalities they provide. Not sure if you have any temporary solution in mind; if so, let us know, as we will be more than happy to look into it.

**Comment by kldeb** [comment]
I can confirm that removing the "thirty-two" npm package from this code base and epic-web's works both locally on my machine and running on aws lambda

**Comment by kldeb** [comment]
PR here: https://github.com/dev-xo/remix-auth-totp/pull/70
