### ISSUE TITLE
[ Question ] Extending OTP Validity Duration

### ISSUE THREAD

**Issue by 684efs3** [dev-xo/remix-auth-totp#71]
Is it possible to configure the OTP to remain valid for a longer duration, such as 10 minutes? If so, how can I modify this setting?

**Comment by dev-xo** [comment]
I think `period` is what you are looking for @684efs3  
- Docs: https://github.com/dev-xo/remix-auth-totp/blob/main/docs/customization.md#totp-generation

```ts
authenticator.use(
  new TOTPStrategy(
    {
      secret: TOTP_SECRET,
      totpGeneration: {
        period: 90,
      },
    },
    async ({ email }) => {
      return getUser(email);
    }
  )
)
```
