### ISSUE TITLE
[ Demo ] Minor UI Improvement

### ISSUE THREAD

**Issue by RushilJalal** [dev-xo/remix-auth-totp#77]
The button and text should not overlap. It makes the site look unprofessional.
I can fix it for you. Thanks.
![image](https://github.com/user-attachments/assets/fa0906ad-2ee5-4567-82ab-7043928fe4d7)

**Comment by dev-xo** [comment]
It's a demo site @RushilJalal, with no intentions at all to look "professional" other than displaying how `remix-auth-totp` works!

The repository is private, but thanks for spotting the minor detail!
