### ISSUE TITLE
Make success redirect optional

### ISSUE THREAD

**Issue by ttizze** [dev-xo/remix-auth-totp#79]
I want to use this library in a dialog, so I don't want to redirect anywhere.
I want to keep the same dialog open after sending the email.
As mentioned in 
[(https://github.com/sergiodxa/remix-auth/discussions/245](https://github.com/sergiodxa/remix-auth/discussions/245)
this should be possible.
Thank you.

**Comment by dev-xo** [comment]
We are open to PRs; the library development is currently on standby.

Please propose and showcase, and we may work on it, rather than requesting.  
Thanks.
